//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDoctors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public int ID { get; set; }
        public string Analysis { get; set; }
        public int AnalysisID { get; set; }
    
        public virtual Analysis Analysis1 { get; set; }
        public virtual DOCTORS_1 DOCTORS_1 { get; set; }
    }
}
