//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Analyses = new HashSet<Analysis>();
        }
    
        public int SSN { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DocrotsID { get; set; }
    
        public virtual ICollection<Analysis> Analyses { get; set; }
        public virtual DOCTORS_1 DOCTORS_1 { get; set; }
    }
}
