//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassPatient111111
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analysis()
        {
            this.Diagnosis = new HashSet<Diagnosis>();
        }
    
        public int ID { get; set; }
        public string Type_of_analysis { get; set; }
        public string State_of_analysis { get; set; }
        public System.DateTime Date_created { get; set; }
        public string Author { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosis> Diagnosis { get; set; }
        public virtual Type_of_analysis Type_of_analysis1 { get; set; }
    }
}
