//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassPatient111111
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer_1
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int LaboratoryID { get; set; }
        public int HospitalID { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Laboratory Laboratory { get; set; }
        public virtual Type_of_analysis Type_of_analysis { get; set; }
    }
}
